stages:
  - lint
  - build

lint:
  image: node:21-alpine
  stage: lint
  script:
   - npm install
   - npm run lint

build-container:
  stage: build
  only:
    - main
  image: docker:latest
  services:
    - docker:dind
  tags:
    - privileged
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest